local global = vim.api.nvim_set_var()

global('loaded_gzip', 1)
global('loaded_tar', 1)
global('loaded_tarPlugin', 1)
global('loaded_zip', 1)
global('loaded_zipPlugin', 1)
global('loaded_vimball', 1)
global('loaded_vimballPlugin', 1)
global('loaded_netrw', 1)
global('loaded_netrwPlugin', 1)
global('loaded_netrwSettings', 1)
global('loaded_netrwFileHandlers', 1)
global('loaded_getscript', 1)
global('loaded_getscriptPlugin', 1)
global('loaded_man', 1)
global('loaded_matchit', 1)
global('loaded_matchparen', 1)
global('loaded_shada_plugin', 1)
global('loaded_spellfile_plugin', 1)
global('loaded_tutor_mode_plugin', 1)
global('did_install_default_menus', 1)
global('did_install_syntax_menu', 1)
global('skip_loading_mswin', 1)
global('did_indent_on', 1)
global('did_load_ftplugin', 1)
global('loaded_rrhelper', 1)
global('loaded_2html_plugin', 1)
