local source = debug.getinfo(1, 'S').source:sub(2)
local plugin = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(source, ':p')))
package.path = plugin .. '/lua/?.lua;' .. package.path
local rewrite = require('features.commit_rewrite')
local model = require('features.commit_model')
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
local function git(args)
  local argv = { 'git', '-C', root }; vim.list_extend(argv, args)
  local r = vim.system(argv, { text = true }):wait(); assert(r.code == 0, r.stderr); return vim.trim(r.stdout or '')
end
local function write(path, text) vim.fn.writefile(text, root .. '/' .. path) end
local function commit(msg) git({ 'add', '.' }); git({ 'commit', '-qm', msg }); return git({ 'rev-parse', 'HEAD' }) end
git({ 'init', '-q', '-b', 'main' }); git({ 'config', 'user.name', 'Test' }); git({ 'config', 'user.email', 'test@example.invalid' })
git({ 'config', 'commit.gpgsign', 'false' }); git({ 'config', 'core.abbrev', '12' })
write('a.txt', { 'initial' }); local initial = commit('root')
local new_root = assert(rewrite.apply(root, initial, { message = { 'new root' } }))
assert(git({ 'rev-parse', 'HEAD' }) == new_root)
write('b.txt', { 'second' }); local second = commit('second')
local rewritten_root = assert(rewrite.apply(root, new_root, { message = { 'rewritten historical root' } }))
assert(git({ 'rev-parse', 'HEAD^' }) == rewritten_root)
assert(git({ 'show', '-s', '--format=%s', 'HEAD' }) == 'second')
-- Reject stale HEAD, unrelated commits, and an ongoing Git operation.
local before = git({ 'rev-parse', 'HEAD' })
assert(not rewrite.apply(root, before, { expected_head = second, message = { 'bad' } }))
assert(not rewrite.apply(root, initial, { message = { 'unrelated' } }))
write('.git/MERGE_HEAD', { rewritten_root })
assert(not rewrite.apply(root, before, { message = { 'during merge' } }))
vim.fn.delete(root .. '/.git/MERGE_HEAD')
assert(git({ 'rev-parse', 'HEAD' }) == before)
-- Merge display selects either parent; rewriting merges preserves topology.
git({ 'checkout', '-qb', 'topic' }); write('topic.txt', { 'topic' }); commit('topic')
git({ 'checkout', '-q', 'main' }); write('main.txt', { 'main' }); commit('main')
git({ 'merge', '--no-ff', '-qm', 'merge topic', 'topic' })
local merge = git({ 'rev-parse', 'HEAD' })
local a, b = assert(model.load(root, merge, 1)), assert(model.load(root, merge, 2))
assert(#a.parents == 2 and a.base ~= b.base)
local merge_reword = assert(rewrite.apply(root, merge, { message = { 'new merge message' } }))
assert(git({ 'show', '-s', '--format=%P', merge_reword }) == table.concat(a.parents, ' '))
write('after.txt', { 'after' }); commit('after merge')
local historical_merge, err = rewrite.apply(root, merge_reword, { message = { 'historical merge' } })
assert(historical_merge, err)
assert(#assert(model.load(root, historical_merge)).parents == 2)
assert(git({ 'rev-parse', 'HEAD^' }) == historical_merge)
-- Remove a whole file from HEAD, keeping it unstaged (Mixed).
local tip = git({ 'rev-parse', 'HEAD' })
local data = assert(model.load(root, tip))
local patch = assert(model.patch(data, data.entries[1]))
local changed, warning = rewrite.apply(root, tip, { patch = patch, reverse = true, mixed = true })
assert(changed, warning)
assert(vim.fn.filereadable(root .. '/after.txt') == 1)
assert(git({ 'status', '--porcelain' }):find('after.txt', 1, true))
-- A rejected patch must not erase dirty user files; stashed index state returns.
write('a.txt', { 'staged user change' }); git({ 'add', 'a.txt' })
write('a.txt', { 'staged user change', 'unstaged' })
local staged, unstaged = git({ 'diff', '--cached' }), git({ 'diff' })
assert(not rewrite.apply(root, changed, { patch = { 'invalid patch' }, reverse = true }))
assert(git({ 'rev-parse', 'HEAD' }) == changed)
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
assert(vim.fn.filereadable(root .. '/after.txt') == 1)
vim.fn.delete(root, 'rf')
print('PASS: HEAD/root/ancestor/merge reword, topology, stale/unrelated/operation guards, Mixed discard, failure recovery')
