
description = ""

# Directories to index.
dirs = [
  "/"
]

# Set to true if you want to index directories
include_dirs = true

# Set to true if you want skip symbolic links
ignore_symlinks = false

# Set to true if you want to ignore hidden files and directories
ignore_hidden = false

