return {
  slash = {
    { label = "/add-dir",          desc = "Add a directory to the allowed list for file access." },
    { label = "/agent",            desc = "Browse and select from available agents." },
    { label = "/clear",            desc = "Clear the conversation history." },
    { label = "/context",          desc = "Show context window token usage and visualization." },
    { label = "/cwd",              desc = "Change working directory or show the current directory." },
    { label = "/delegate",         desc = "Delegate changes to a remote repository with an AI-generated PR." },
    { label = "/exit",             desc = "Exit the CLI." },
    { label = "/quit",             desc = "Exit the CLI." },
    { label = "/share",            desc = "Share session to a markdown file or GitHub gist." },
    { label = "/feedback",         desc = "Provide feedback about the CLI." },
    { label = "/help",             desc = "Show help for interactive commands." },
    { label = "/list-dirs",        desc = "Display all allowed directories for file access." },
    { label = "/login",            desc = "Log in to Copilot." },
    { label = "/logout",           desc = "Log out of Copilot." },
    { label = "/mcp",              desc = "Manage MCP server configuration (show/add/edit/delete/disable/enable)." },
    { label = "/model",            desc = "Select AI model to use." },
    { label = "/reset-allowed-tools", desc = "Reset the list of allowed tools." },
    { label = "/session",          desc = "Show information about the current CLI session." },
    { label = "/skills",           desc = "Manage skills (list/info/add/remove/reload)." },
    { label = "/terminal-setup",   desc = "Configure terminal for multiline input support." },
    { label = "/theme",            desc = "View or configure terminal theme (auto/dark/light)." },
    { label = "/usage",            desc = "Display session usage metrics and statistics." },
    { label = "/user",             desc = "Manage GitHub user list (show/list/switch)." },
  },
  at = {
    { label = "@repo",        desc = "Reference the whole repository context." },
    { label = "@workspace",   desc = "Use the current workspace context." },
    { label = "@file",        desc = "Use the current file content." },
    { label = "@selection",   desc = "Use the current visual selection." },
    { label = "@changes",     desc = "Use the current git diff/changes." },
    { label = "@diagnostics", desc = "Include diagnostics and lint messages." },
    { label = "@recent",      desc = "Refer to recent edits or history." },
    { label = "@api",         desc = "Pull in API or doc snippets." },
  },
}
