return {
  slash = {
    { label = "/about",            desc = "Show version info." },
    { label = "/auth",             desc = "Change the auth method." },
    { label = "/bug",              desc = "Submit a bug report." },
    { label = "/chat",             desc = "Manage conversation history (/chat list|save|resume|delete|share)." },
    { label = "/clear",            desc = "Clear the screen and conversation history." },
    { label = "/compress",         desc = "Compress the context by replacing it with a summary." },
    { label = "/copy",             desc = "Copy the last result or code snippet to clipboard." },
    { label = "/docs",             desc = "Open full Gemini CLI documentation in your browser." },
    { label = "/directory",        desc = "Manage workspace directories (/directory add|show)." },
    { label = "/editor",           desc = "Set external editor preference." },
    { label = "/extensions",       desc = "Manage extensions (/extensions list|update|explore|restart)." },
    { label = "/help",             desc = "Help for gemini-cli." },
    { label = "/ide",              desc = "Manage IDE integration." },
    { label = "/init",             desc = "Analyze the project and create a tailored GEMINI.md file." },
    { label = "/mcp",              desc = "Manage MCP servers (/mcp list|desc|schema|auth|refresh)." },
    { label = "/memory",           desc = "Interact with memory (/memory show|add|refresh|list)." },
    { label = "/model",            desc = "Configure the model." },
    { label = "/privacy",          desc = "Display the privacy notice." },
    { label = "/policies",         desc = "Manage policies (/policies list)." },
    { label = "/quit",             desc = "Exit the CLI." },
    { label = "/resume",           desc = "Browse and resume auto-saved conversations." },
    { label = "/stats",            desc = "Check session stats (/stats session|model|tools)." },
    { label = "/theme",            desc = "Change the theme." },
    { label = "/tools",            desc = "List available Gemini CLI tools. Usage: /tools [desc]." },
    { label = "/settings",         desc = "View and edit Gemini CLI settings." },
    { label = "/vim",              desc = "Toggle vim mode on/off." },
    { label = "/setup-github",     desc = "Set up GitHub Actions." },
    { label = "/terminal-setup",   desc = "Configure terminal keybindings for multiline input." },
    { label = "!",                 desc = "Run a shell command." },
    { label = "[MCP]",             desc = "Model Context Protocol command from external servers." },
  },
  at = {
    { label = "@docs", desc = "Insert docs context." },
    { label = "@api",  desc = "Insert API context." },
    { label = "@spec", desc = "Insert spec context." },
  },
}
