git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  sidePanelWidth: 0.25
  timeFormat: '2006-01-02 15:04:05'
  showIcons: true
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
refresher:
  refreshInterval: 3
os:
  edit: 'nvim-remote'
