[language.javascript]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-tsserver/node_modules/.bin/tsserver"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false

[language.typescript]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-tsserver/node_modules/.bin/tsserver"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false

[language.php]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-phpls/node_modules/.bin/intelephense"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false
synchronous_triggers = ["->"]
synchronous_timeout_ms = 1000

[language.html]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-html/node_modules/.bin/tsc"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false

[language.css]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-css/lib/server.js"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false

[language.scss]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-css/lib/server.js"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false

[language.rust]
command = "/home/aikawa/.config/coc/extensions/node_modules/coc-rust-analyzer/lib/index.js"
args = ["--stdio"]
num_server_instances = 2
always_prefer = false
