local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  rocks = { hererocks = true },
  spec = {
    { import = "plugins.nightfox" },
    { import = "plugins.project" },
    { import = "plugins.conform"},
    { import = "plugins.lint"},
    { import = "plugins.dressing" },
    { import = "plugins.lightbulb" },
    { import = "plugins.illuminate" },
    { import = "plugins.refactoring" },
    { import = "plugins.notify" },
    { import = "plugins.noice" },
    { import = "plugins.tiny-inline-diagnostic" },
    { import = "plugins.hlchunk" },
    { import = "plugins.outline" },
    { import = "plugins.avante" },
    { import = "plugins.colorizer" },
    { import = "plugins.insx" },
    -- { import = "plugins.automa" },
    { import = "plugins.comment" },
    { import = "plugins.yanky" },
    { import = "plugins.flash" },
    { import = "plugins.quick-scope" },
    { import = "plugins.multicursors" },
    { import = "plugins.asterisk" },
    { import = "plugins.edgemotion" },
    { import = "plugins.migemo-search" },
    { import = "plugins.textobjs" },
    { import = "plugins.substitute" },
    { import = "plugins.smartchr" },
    { import = "plugins.hydra" },
    { import = "plugins.surround" },
    { import = "plugins.matchup" },
    { import = "plugins.treesj" },
    { import = "plugins.neogen" },
    { import = "plugins.neo-tree" },
    { import = "plugins.bqf" },
    { import = "plugins.harpoon" },
    { import = "plugins.fzf-lua" },
    { import = "plugins.render_markdown" },
    { import = "plugins.time-machine" },
    { import = "plugins.grug-far" },
    { import = "plugins.junkfile" },
    { import = "plugins.guess-indent" },
    { import = "plugins.dbee" },
    { import = "plugins.tmux" },
    -- { import = "plugins.gitgutter" },
    { import = "plugins.gitsigns" },
    { import = "plugins.fugitive" }, -- 5cfbc35aa8381f3e199be248fbb94b05c16f82ff
    { import = "plugins.diffview" },
    { import = "plugins.lualine" },
    { import = "plugins.bufferline" },
    { import = "plugins.myutil" },
    { import = "plugins.dial" },
    { import = "plugins.toggleterm" },
    { import = "plugins.treesitter" },
    { import = "plugins.bufjump" },
    { import = "plugins.gitlinker" },
    { import = "plugins.others" },
    { import = "plugins.incline" },
    { import = "plugins.undo-glow" },
    { import = "plugins.kitty-scrollback" },
    { import = "plugins.trouble" },
    { import = "plugins.neotest" },
    { import = "plugins.overseer" },
    { import = "plugins.resession" },
    { import = "plugins.kulala" },
    { import = "plugins.octo" },
    { import = "plugins.oil" },
    { import = "plugins.relativenumber" },
    { import = "plugins.typescript-tools" },
    { import = "plugins.luasnip" },
    { import = "plugins.blink" },
    -- { import = "plugins.nvim-cmp" },
    { "neovim/nvim-lspconfig", event = "BufReadPre", config = function () require"lsp" end, },
    { "mason-org/mason.nvim", lazy = true },
    -- { "williamboman/mason-lspconfig.nvim", lazy = true },
    { "rafamadriz/friendly-snippets", lazy = true },
    -- { "onsails/lspkind-nvim", lazy = true },
    { "kyazdani42/nvim-web-devicons", lazy = true },
    { "MunifTanjim/nui.nvim", lazy = true },
    { "ethanholz/nvim-lastplace", config = true },
    { "nvim-lua/plenary.nvim", lazy = true },
    { "3rd/image.nvim", lazy = true, commit = "21909e3"},
    { "xzbdmw/colorful-menu.nvim", lazy = true },
    { "Saghen/blink.compat", lazy = true },
    { "honza/vim-snippets", event = "InsertEnter" },
    { "kana/vim-niceblock", event = "BufRead" },
    { "stevearc/quicker.nvim", ft = "qf", config = true },
    { "mrcjkb/rustaceanvim", ft = "rust" },
    { "akinsho/git-conflict.nvim", config = true },
    { "aikawa9376/vim-auto-cursorline", event = "BufRead" },
    { "aikawa9376/neomru.vim", event = "BufReadPre" },
    { "cseickel/diagnostic-window.nvim", cmd = { "DiagWindowShow" } },
    { "vim-scripts/BufOnly.vim", cmd = { "BufOnly" } },
    { "moll/vim-bbye", cmd = { "Bdelete", "Bwipeout" } },
  },
  performance = {
    rtp = {
      disabled_plugins = {
        "gzip",
        "matchit",
        "matchparen",
        "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
