local plugin = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p')))
package.path = plugin .. '/lua/?.lua;' .. package.path
local m = require('git.features.blame_model')
local hash = string.rep('a', 40)
local rows, lines = m.parse(hash .. ' 4 1 2\nauthor 日本語\nauthor-time 100\nsummary subject\nprevious ' .. hash .. ' "old\\tname.txt"\nfilename "\\346\\227\\245.txt"\n\t\n' .. hash .. ' 5 2\nauthor 日本語\nauthor-time 100\nfilename "\\346\\227\\245.txt"\n\tcode\n')
assert(#rows == 2 and lines[1] == '' and lines[2] == 'code')
assert(rows[1].path == '日.txt' and rows[1].previous_path == 'old\tname.txt')
assert(rows[1].original == 4 and rows[2].original == 5)
assert(m.old_line('a\nb\nc\n', 'a\nx\ny\nb\nc\n', 4) == 2)
assert(m.old_line('a\nb\nc\n', 'a\nc\n', 2) == 3)
assert(m.old_line('a\nb\nc\n', 'a\nB\nc\n', 2) == 2)
assert(m.old_line('', 'new\n', 1) == 1)
print('PASS: porcelain empty lines, Unicode/quoted paths, previous metadata, old-line insertion/deletion mapping')
