local plugin = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p')))
package.path = plugin .. '/lua/?.lua;' .. package.path
vim.opt.rtp:prepend(plugin)
local root = vim.fn.tempname() .. ' repo'; vim.fn.mkdir(root, 'p')
local objects = require('git.objects')
local function git(args) return vim.trim(objects.run(root, args)) end
git({ 'init', '-q', '-b', 'main' }); git({ 'config', 'user.name', 'Test' }); git({ 'config', 'user.email', 'test@example.invalid' }); git({ 'config', 'commit.gpgsign', 'false' })
vim.fn.writefile({ 'one', 'two' }, root .. '/a file.txt')
git({ 'add', '.' }); git({ 'commit', '-qm', 'first' }); local first = git({ 'rev-parse', 'HEAD' })
vim.fn.writefile({ 'changed', 'two' }, root .. '/a file.txt')
require('git').setup()
vim.cmd('edit ' .. vim.fn.fnameescape(root .. '/a file.txt'))
local work = vim.api.nvim_get_current_buf()
assert(objects.context() == root, 'buffer repository must win over cwd')
vim.cmd('Gwrite'); assert(git({ 'show', ':a file.txt' }):match('changed'))
vim.cmd('Gedit'); assert(vim.b.git_object.stage == '0' and vim.bo.modifiable)
vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'index only' }); vim.cmd('write')
assert(git({ 'show', ':a file.txt' }):match('index only'))
assert(vim.fn.readfile(root .. '/a file.txt')[1] == 'changed', 'index write changed worktree')
local index = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'stale' })
git({ 'add', '--', 'a file.txt' })
assert(not pcall(vim.cmd, 'write'), 'stale index must reject write')
vim.cmd('edit!')
vim.cmd('Gvdiffsplit'); assert(vim.wo.diff)
assert(#vim.api.nvim_list_wins() == 2)
vim.cmd('only'); vim.cmd('diffoff')
vim.cmd('buffer ' .. work)
vim.cmd('Gedit "HEAD:a file.txt"'); assert(vim.api.nvim_get_current_line() == 'one' and vim.bo.readonly)
package.path = vim.fs.dirname(plugin) .. '/lazyagent/lua/?.lua;' .. package.path
local notes = require('lazyagent.note_source')
local captured = notes.capture(vim.api.nvim_get_current_buf(), root, 1, 1)
assert(captured.path == 'a file.txt' and captured.revision == first)
local name = vim.api.nvim_buf_get_name(0); vim.cmd('bdelete')
local restored = assert(notes.fugitive_buffer(captured, false), 'Native Note blob did not reopen')
vim.api.nvim_set_current_buf(restored)
assert(vim.api.nvim_get_current_line() == 'one')
vim.cmd('edit ' .. vim.fn.fnameescape(name)); assert(vim.api.nvim_get_current_line() == 'one')
vim.cmd('buffer ' .. work)
vim.cmd('Gread HEAD:%'); assert(vim.api.nvim_get_current_line() == 'one' and vim.bo.modified)
assert(not pcall(vim.cmd, 'Gread'), 'modified buffer needs bang')
vim.cmd('Gread!'); assert(vim.api.nvim_get_current_line() == 'changed')
vim.cmd('write')
vim.cmd('Gclog!'); local qf = vim.fn.getqflist(); assert(#qf == 1)
vim.cmd('cclose'); vim.cmd('cc'); assert(vim.api.nvim_get_current_line() == 'one')
vim.cmd('Gedit HEAD'); assert(vim.b.custom_git_commit and vim.b.fugitive_commit == first)
vim.cmd('Gedit HEAD:')
assert(vim.bo.filetype == 'git')
vim.fn.maparg('<CR>', 'n', false, true).callback()
assert(vim.api.nvim_get_current_line() == 'one', 'Tree entry did not open its blob')
vim.cmd('Gedit HEAD')
vim.cmd('Ggraph native'); assert(vim.api.nvim_buf_get_lines(0, 0, -1, false)[1]:find('first', 1, true)); vim.cmd('close')
vim.cmd('buffer ' .. work)
vim.cmd('Git! commit -m "second message"'); assert(git({ 'log', '-1', '--format=%s' }) == 'second message')
vim.cmd('GeditHeadAtFile')
assert(require('git.features.commit').entry_at(vim.api.nvim_get_current_buf(), vim.fn.line('.')).path == 'a file.txt')
vim.cmd('buffer ' .. work)
vim.cmd('Gmove "renamed file.txt"'); assert(vim.api.nvim_buf_get_name(0) == root .. '/renamed file.txt')
assert(vim.fn.exists('*FugitiveGitDir') == 0 and not package.loaded['features.commit'])
-- Linked worktrees must resolve their own root/index from file buffers.
local linked = root .. '-linked'; git({ 'worktree', 'add', '-qb', 'linked', linked })
vim.cmd('edit ' .. vim.fn.fnameescape(linked .. '/a file.txt'))
assert(objects.context() == linked)
vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'linked' }); vim.cmd('Gwrite')
assert(vim.trim(objects.run(linked, { 'show', ':a file.txt' })):match('linked'))
assert(not git({ 'show', ':renamed file.txt' }):match('linked'))
for _, b in ipairs(vim.api.nvim_list_bufs()) do pcall(vim.api.nvim_buf_delete, b, { force = true }) end
vim.fn.delete(root, 'rf'); vim.fn.delete(linked, 'rf')
print('PASS: standalone commands, paths with spaces, index writes/stale guard, diff, quickfix reload, commit, move, linked worktree')
