"""Generate pinned Unicode tables from regex 1.12.2 and unicode-segmentation 1.12.0.

Usage: python3 tests/generate_delta_unicode.py <perl_word.rs> <tables.rs>
Sources: https://github.com/rust-lang/regex/tree/1.12.2/regex-syntax/src/unicode_tables
         https://github.com/unicode-rs/unicode-segmentation/tree/v1.12.0/src
These are the Unicode 16 tables used by delta 0.19.2 (MIT/Apache-2.0).
"""
import re
import sys
from pathlib import Path


def scalar(s):
    if s.startswith(r"\u{"):
        return int(s[3:-1], 16)
    return ord(s)


word = re.findall(r"\('([^']+)', '([^']+)'\)", Path(sys.argv[1]).read_text())
grapheme = Path(sys.argv[2]).read_text().split('const grapheme_cat_table:')[1].split('];')[0]
classes = ['Any', 'CR', 'Control', 'Extend', 'Extended_Pictographic', 'InCB_Consonant',
           'L', 'LF', 'LV', 'LVT', 'Prepend', 'Regional_Indicator', 'SpacingMark', 'T', 'V', 'ZWJ']
out = ['-- Generated by tests/generate_delta_unicode.py; Unicode 16.0, MIT/Apache-2.0.',
       '-- Source versions and licenses: see THIRD_PARTY_NOTICES.md.', 'return {', '  word = {']
for a, b in word:
    out.append(f'    {{ 0x{scalar(a):X}, 0x{scalar(b):X} }},')
out.extend(['  },', '  grapheme = {'])
for a, b, c in re.findall(r"\('([^']+)',\s*'([^']+)',\s*GC_(\w+)\)", grapheme):
    # Hangul syllable categories are computed algorithmically.
    if c not in ['LV', 'LVT']:
        out.append(f'    {{ 0x{scalar(a):X}, 0x{scalar(b):X}, {classes.index(c)} }},')
out.extend(['  },', '}'])
target = Path(__file__).resolve().parents[1] / 'lua/git/features/delta_unicode.lua'
target.write_text('\n'.join(out) + '\n')
print(f'Generated {len(word)} word ranges and {len(out) - len(word) - 7} grapheme ranges')
