local source = debug.getinfo(1, 'S').source:sub(2)
local plugin = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(source, ':p')))
package.path = plugin .. '/lua/?.lua;' .. package.path
local edits = require('git.features.history_edits')
local history = require('git.features.history_rewrite')
local root = vim.fn.tempname() .. ' repo space'; vim.fn.mkdir(root, 'p')
local function git(args)
  local argv = { 'git', '-C', root }; vim.list_extend(argv, args)
  local r = vim.system(argv, { text = false }):wait(); assert(r.code == 0, r.stderr); return vim.trim(r.stdout or '')
end
local function write(path, lines) vim.fn.writefile(lines, root .. '/' .. path) end
local function commit(msg) git({ 'add', '.' }); git({ 'commit', '-qm', msg }); return git({ 'rev-parse', 'HEAD' }) end
local function success(hash, warning) assert(hash, warning); assert(not warning, warning); return hash end
local function clean() assert(git({ 'status', '--porcelain' }) == '') end
git({ 'init', '-q', '-b', 'main' }); git({ 'config', 'user.name', 'Test' }); git({ 'config', 'user.email', 'test@example.invalid' })
git({ 'config', 'commit.gpgsign', 'false' }); git({ 'config', 'core.abbrev', '12' })
git({ 'config', 'rebase.autoSquash', 'true' }); git({ 'config', 'rebase.updateRefs', 'true' })
write('base', { 'base' }); write('user', { 'tracked' }); local base = commit('base')
write('a', { 'a' }); local a = commit('a')
git({ 'branch', 'retained-a', a }); local retained_a = a
write('b', { 'b' }); local b = commit('b')
write('c', { 'c' }); local c = commit('c')
-- Exact hashes despite core.abbrev, both move directions, unchanged tip tree.
local tree = git({ 'rev-parse', 'HEAD^{tree}' })
success(edits.move(root, b:sub(1, 9), a:sub(1, 9), 'down'))
assert(git({ 'log', '--format=%s', '-4' }) == 'c\na\nb\nbase')
assert(git({ 'rev-parse', 'HEAD^{tree}' }) == tree); clean()
assert(git({ 'rev-parse', 'retained-a' }) == retained_a, 'only the current branch should be rewritten')
a, b = git({ 'rev-parse', 'HEAD^' }), git({ 'rev-parse', 'HEAD^^' })
success(edits.move(root, b, a, 'up'))
assert(git({ 'log', '--format=%s', '-4' }) == 'c\nb\na\nbase'); clean()
-- Dirty state and an existing stash survive a middle-commit drop.
write('base', { 'older stash' }); git({ 'stash', 'push', '-qm', 'existing' })
local previous_stash = git({ 'rev-parse', 'refs/stash' })
write('base', { 'staged' }); git({ 'add', 'base' }); write('base', { 'staged', 'unstaged' }); write('untracked', { 'untouched' })
local staged, unstaged = git({ 'diff', '--cached' }), git({ 'diff' })
success(edits.drop(root, { git({ 'rev-parse', 'HEAD^' }):sub(1, 8) }))
assert(git({ 'log', '--format=%s', '-3' }) == 'c\na\nbase')
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
assert(vim.fn.readfile(root .. '/untracked')[1] == 'untouched')
assert(git({ 'rev-parse', 'refs/stash' }) == previous_stash)
git({ 'reset', '--hard', 'HEAD' }); vim.fn.delete(root .. '/untracked')
-- Folding into the root works, including a multiline replacement message.
write('base', { 'base', 'index contribution' }); git({ 'add', 'base' })
write('base', { 'base', 'index contribution', 'unstaged survives' }); write('untracked', { 'keep' })
success(edits.mix_index(root, base, 'reworded root\n\nbody'))
assert(git({ 'show', 'HEAD:base' }) == 'base\nindex contribution')
assert(git({ 'diff', '--cached' }) == '', 'index contribution must be consumed')
assert(git({ 'diff' }):find('+unstaged survives', 1, true))
assert(vim.fn.readfile(root .. '/untracked')[1] == 'keep')
assert(git({ 'show', '-s', '--format=%B', 'HEAD~2' }) == 'reworded root\n\nbody')
assert(git({ 'rev-parse', 'refs/stash' }) == previous_stash)
git({ 'reset', '--hard', 'HEAD' }); vim.fn.delete(root .. '/untracked')
-- Empty index reword, normal index fixup, and parent fixup (including root parent).
success(edits.mix_index(root, git({ 'rev-parse', 'HEAD' }), 'renamed c')); clean()
write('base', { 'base', 'index contribution', 'second staged contribution' }); git({ 'add', 'base' })
success(edits.mix_index(root, git({ 'rev-parse', 'HEAD^' }))); clean()
assert(git({ 'show', 'HEAD:base' }):find('second staged contribution', 1, true))
success(edits.fixup(root, git({ 'rev-parse', 'HEAD^' }))); clean()
assert(git({ 'rev-list', '--count', 'HEAD' }) == '2')
assert(git({ 'show', 'HEAD:a' }) == 'a')
-- A conflicting swap aborts, restores original HEAD and exact dirty/index state.
git({ 'reset', '--hard', base })
write('base', { 'first dependent edit' }); local first = commit('first dependent')
write('base', { 'second dependent edit' }); local second = commit('second dependent')
write('tip', { 'tracked' }); local tip = commit('user')
write('user', { 'staged user' }); git({ 'add', 'user' }); write('user', { 'staged user', 'unstaged user' }); write('untracked', { 'keep' })
staged, unstaged = git({ 'diff', '--cached' }), git({ 'diff' })
local moved, err = edits.move(root, second, first, 'down')
assert(not moved and err, 'conflicting reorder must fail')
assert(git({ 'rev-parse', 'HEAD' }) == tip)
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
assert(vim.fn.readfile(root .. '/untracked')[1] == 'keep')
assert(vim.fn.isdirectory(root .. '/.git/rebase-merge') == 0)
assert(git({ 'rev-parse', 'refs/stash' }) == previous_stash)
-- A failed fixup must undo its helper commit and restore the original index.
write('.git/hooks/pre-commit', { '#!/bin/sh', 'exit 1' }); vim.fn.setfperm(root .. '/.git/hooks/pre-commit', 'rwxr-xr-x')
local mixed, mix_err = edits.mix_index(root, first)
assert(not mixed and mix_err)
assert(git({ 'rev-parse', 'HEAD' }) == tip)
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
vim.fn.delete(root .. '/.git/hooks/pre-commit')
-- Failure during autosquash replay also removes the newly created helper commit.
write('base', { 'staged dependent edit' }); git({ 'add', 'base' }); write('base', { 'staged dependent edit', 'unstaged dependent edit' })
local conflict_staged, conflict_unstaged = git({ 'diff', '--cached' }), git({ 'diff' })
mixed, mix_err = edits.mix_index(root, first)
assert(not mixed and mix_err)
assert(git({ 'rev-parse', 'HEAD' }) == tip)
assert(git({ 'diff', '--cached' }) == conflict_staged and git({ 'diff' }) == conflict_unstaged)
assert(vim.fn.isdirectory(root .. '/.git/rebase-merge') == 0)
git({ 'restore', '--staged', '--worktree', '--source=HEAD', 'base' })
-- Reject invalid/outside targets, merge drops and deleting every commit before mutations.
assert(not edits.move(root, first, base, 'up'))
assert(not edits.drop(root, { a }))
assert(not edits.drop(root, vim.split(git({ 'rev-list', 'HEAD' }), '\n')))
assert(git({ 'rev-parse', 'HEAD' }) == tip)
local tx = success(history.prepare(root, { tip }))
local failed, failure = history.execute(tx, function()
  tx:rebase(base, { action = 'drop', commits = { string.rep('f', 40) } })
end)
assert(not failed and failure:find('missing selected commit', 1, true))
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
assert(git({ 'rev-parse', 'HEAD' }) == tip)
-- Suffix drop uses reset internally, still restoring the saved worktree.
success(edits.drop(root, { tip, second }))
assert(git({ 'rev-parse', 'HEAD' }) == first)
assert(git({ 'diff', '--cached' }) == staged and git({ 'diff' }) == unstaged)
-- Merge/side-branch targets are rejected without changing the repository.
git({ 'reset', '--hard', 'HEAD' }); vim.fn.delete(root .. '/untracked')
git({ 'checkout', '-qb', 'topic', base }); write('topic', { 'topic' }); local topic = commit('topic')
git({ 'checkout', '-q', 'main' }); git({ 'merge', '--no-ff', '-qm', 'merge topic', 'topic' })
local merge = git({ 'rev-parse', 'HEAD' })
assert(not edits.drop(root, { merge }))
assert(not edits.move(root, merge, first, 'down'))
assert(not edits.fixup(root, merge))
assert(not edits.mix_index(root, merge, 'reword merge'))
assert(not edits.drop(root, { topic }))
assert(git({ 'rev-parse', 'HEAD' }) == merge); clean()
-- Root-boundary moves and selective root drop work on independent changes.
git({ 'checkout', '-qB', 'root-move', retained_a })
tree = git({ 'rev-parse', 'HEAD^{tree}' })
success(edits.move(root, retained_a, base, 'down'))
assert(git({ 'log', '--format=%s', '-2' }) == 'base\na')
assert(git({ 'rev-parse', 'HEAD^{tree}' }) == tree); clean()
git({ 'checkout', '-qB', 'root-drop', retained_a })
success(edits.drop(root, { base }))
assert(git({ 'rev-list', '--count', 'HEAD' }) == '1')
assert(git({ 'show', 'HEAD:a' }) == 'a'); clean()
vim.fn.delete(root, 'rf')
print('PASS: move/drop/fixup/index rewrite, root support, full hashes, dirty split, owned-stash recovery, conflict rollback')
