-- Run from the plugin root: nvim --headless --clean -u NONE -l tests/wip.lua
local source = debug.getinfo(1, 'S').source:sub(2)
local plugin = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(source, ':p')))
package.path = plugin .. '/lua/?.lua;' .. package.path
local root = vim.fn.tempname()
vim.fn.mkdir(root, 'p')
local function git(args)
  local cmd = { 'git', '-C', root }
  vim.list_extend(cmd, args)
  local result = vim.system(cmd, { text = true }):wait()
  assert(result.code == 0, result.stderr)
  return vim.trim(result.stdout or '')
end
git({ 'init', '-q', '-b', 'main' })
git({ 'config', 'user.name', 'Test' })
git({ 'config', 'user.email', 'test@example.invalid' })
vim.fn.writefile({ 'one', 'two' }, root .. '/file.txt')
git({ 'add', '.' })
git({ 'commit', '-qm', 'base' })
vim.fn.writefile({ 'ONE', 'two' }, root .. '/file.txt')
git({ 'add', 'file.txt' })
vim.fn.writefile({ 'ONE', 'TWO' }, root .. '/file.txt')
local before = git({ 'status', '--porcelain=v1' })
local wip = require('git.features.wip')
local ok, saved = wip.save(root)
assert(ok and saved ~= 'unchanged', saved)
assert(git({ 'status', '--porcelain=v1' }) == before, 'saving changed the worktree/index')
local entries = assert(wip.list(root))
assert(#entries == 1 and entries[1].hash == saved)
assert(wip.save(root) == true and #assert(wip.list(root)) == 1, 'unchanged state duplicated')
git({ 'reset', '--hard', '-q', 'HEAD' })
local restored, err = wip.restore(root, '0')
assert(restored, err)
assert(git({ 'status', '--porcelain=v1' }) == before, 'restore lost the staged/unstaged split')
assert(vim.fn.readfile(root .. '/file.txt')[2] == 'TWO')
assert(not wip.restore(root, '0'), 'dirty restore was accepted')
vim.fn.writefile({ 'ONE', 'two' }, root .. '/file.txt')
git({ 'add', 'file.txt' })
vim.fn.writefile({ 'ONE', 'new' }, root .. '/file.txt')
assert(wip.save(root))
assert(#assert(wip.list(root)) == 2)
git({ 'reset', '--hard', '-q', 'HEAD' })
assert(wip.restore(root, '1'), 'older snapshot could not be restored')
assert(vim.fn.readfile(root .. '/file.txt')[2] == 'TWO')
git({ 'reset', '--hard', '-q', 'HEAD' })
git({ 'checkout', '-qb', 'other' })
assert(#assert(wip.list(root)) == 0, 'snapshots leaked across branches')
wip.setup(vim.api.nvim_create_augroup('WipTest', { clear = true }))
vim.g.git_wip_enabled = true
vim.cmd('edit ' .. vim.fn.fnameescape(root .. '/file.txt'))
vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'automatic' })
vim.cmd('write')
assert(vim.wait(5000, function() return #assert(wip.list(root)) == 1 end, 50),
  'enabled WIP did not save after a file write')
vim.g.git_wip_enabled = false
vim.fn.delete(root, 'rf')
print('PASS: WIP snapshot history, no-op deduplication, branch isolation, and indexed restore')
